//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leaf.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leaf.Controls.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }

        internal static string ImageViewer_SelectMode {
            get {
                return ResourceManager.GetString("ImageViewer_SelectMode", resourceCulture);
            }
        }

        internal static string ImageViewer_SelectModeTip {
            get {
                return ResourceManager.GetString("ImageViewer_SelectModeTip", resourceCulture);
            }
        }

        internal static string ImageViewer_PanMode {
            get {
                return ResourceManager.GetString("ImageViewer_PanMode", resourceCulture);
            }
        }

        internal static string ImageViewer_PanModeTip {
            get {
                return ResourceManager.GetString("ImageViewer_PanModeTip", resourceCulture);
            }
        }

        internal static string ImageViewer_DrawRoi {
            get {
                return ResourceManager.GetString("ImageViewer_DrawRoi", resourceCulture);
            }
        }

        internal static string ImageViewer_DrawRoiTip {
            get {
                return ResourceManager.GetString("ImageViewer_DrawRoiTip", resourceCulture);
            }
        }

        internal static string ImageViewer_EditRoi {
            get {
                return ResourceManager.GetString("ImageViewer_EditRoi", resourceCulture);
            }
        }

        internal static string ImageViewer_EditRoiTip {
            get {
                return ResourceManager.GetString("ImageViewer_EditRoiTip", resourceCulture);
            }
        }

        internal static string ImageViewer_DeleteRoi {
            get {
                return ResourceManager.GetString("ImageViewer_DeleteRoi", resourceCulture);
            }
        }

        internal static string ImageViewer_DeleteRoiTip {
            get {
                return ResourceManager.GetString("ImageViewer_DeleteRoiTip", resourceCulture);
            }
        }

        internal static string ImageViewer_ClearRois {
            get {
                return ResourceManager.GetString("ImageViewer_ClearRois", resourceCulture);
            }
        }

        internal static string ImageViewer_ClearRoisTip {
            get {
                return ResourceManager.GetString("ImageViewer_ClearRoisTip", resourceCulture);
            }
        }

        internal static string ImageViewer_FitToView {
            get {
                return ResourceManager.GetString("ImageViewer_FitToView", resourceCulture);
            }
        }

        internal static string ImageViewer_FitToViewTip {
            get {
                return ResourceManager.GetString("ImageViewer_FitToViewTip", resourceCulture);
            }
        }

        internal static string ImageViewer_AdjustRoiPosition {
            get {
                return ResourceManager.GetString("ImageViewer_AdjustRoiPosition", resourceCulture);
            }
        }
    }
}
